python scripts/scaling/final.py -k mmlu-var -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_mmlu-var.png
python scripts/scaling/final.py -k hellaswag-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_hellaswag-5shot.png
python scripts/scaling/final.py -k arc-e-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_arc-e-5shot.png
python scripts/scaling/final.py -k arc-c-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_arc-c-5shot.png
python scripts/scaling/final.py -k piqa-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_piqa-5shot.png
python scripts/scaling/final.py -k winogrande-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_winogrande-5shot.png
python scripts/scaling/final.py -k openbookqa-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_openbookqa-5shot.png
python scripts/scaling/final.py -k boolq-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_boolq-5shot.png
python scripts/scaling/final.py -k sciq-0shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_sciq-0shot.png
python scripts/scaling/final.py -k copa-0shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_copa-0shot.png
python scripts/scaling/final.py -k csqa-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_csqa-5shot.png
python scripts/scaling/final.py -k socialiqa-5shot -c scripts/scaling/final_peteish.json -o figure/peteish-final/final_socialiqa-5shot.png
