[project]
name = "ai2-llm-filters"
version = "0.4.0"
description = "Data filters"
authors = [
    {name = "Aakanksha Naik", email = "aakankshan@allenai.org" },
    {name = "Abhilasha Ravichander", email = "abhilashar@allenai.org" },
    {name = "Ian Magnusson", email = "ianm@allenai.org" },
    {name = "Khyathi Chandu", email = "khyathic@allenai.org" },
    {name = "Kyle Lo", email = "kylel@allenai.org" },
    {name = "Luca Soldaini", email = "lucas@allenai.org" },
    {name = "Rodney Kinney", email = "rodneyk@allenai.org" }
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "tqdm",
    "boto3",
    "cached-path==1.3.4",
    "msgspec==0.14.2",
    "smashed[remote]==0.20.0",
    "presidio_analyzer==2.2.32",
    "pycld2==0.41",
    "pycld3==0.22",
    "blingfire==0.1.8",
    "fasttext==0.9.2",
    "tokenizers==0.13.3",
    "unidecode",
    "uniseg",
    "termcolor==2.3.0"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/allenai/llm"


[project.scripts]
ai2_llm_filters = "ai2_llm_filters.core_tools.runtime:TaggerProcessor.main"
ai2_llm_filters_viz = "ai2_llm_filters.core_tools.vizualizer:Visualizer.main"
ai2_llm_filters_pre = "ai2_llm_filters.core_tools.vizualizer:RawPreviewer.main"


[project.optional-dependencies]
dev = [
    "black>=22.6.0",
    "isort>=5.10.1",
    "mypy>=0.971",
    "pytest>=5.2",
    "ipython>=8.4.0",
    "autopep8>=1.7.0",
    "flake8>=5.0",
    "ipdb>=0.13.0",
    "flake8-pyi>=22.8.1",
    "Flake8-pyproject>=1.1.0",
]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 61.0.0",
    "wheel"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ai2_llm_filters = ["py.typed"]

[tool.black]
line-length = 115

include = '\.pyi?$'

exclude = '''
(
      __pycache__
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vscode
    | \.venv
    | \bdist\b
    | \bdoc\b
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.autopep8]
max_line_length = 115
in-place = true
recursive = true
aggressive = 3

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
no_site_packages = true
allow_redefinition = false
warn_unused_configs = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = false
warn_unreachable = true
show_error_codes = true
pretty = true

[tool.mypy-tests]
strict_optional = false

[tool.flake8]
per-file-ignores = [
    '__init__.py:F401',
    '*.pyi:E302,E305',
    '*.py:E203'
]
