# Defines a CUDA-enabled Docker image suitable for running this project's experiments
# via beaker-gantry.
#
# To build and push the image to Beaker, run 'make gantry-image'.
# To test the image after pushing to Beaker, run 'make gantry-test'.

FROM dolma-base

WORKDIR /stage

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/dolma
