# Defines a CUDA-enabled Docker image suitable for running this project's experiments
# via beaker-gantry.
#
# To build and push the image to Beaker, run 'make gantry-image'.
# To test the image after pushing to Beaker, run 'make gantry-test'.

FROM olmo-torch2-base

WORKDIR /stage

COPY pyproject.toml .
RUN mkdir olmo && touch olmo/__init__.py && \
    pip install --no-cache-dir .[all] && \
    pip uninstall -y ai2-olmo && \
    rm -rf olmo/

WORKDIR /app/olmo
