# CONFIGS = {
#     # '20m': {
#     #     'path': 'wandb/tiny-olmo-20M-rms-norm-adam-eps-1e-8-lr-6e-4-emb-wd-merged_val-all.csv',
#     #     'keys': VAL_KEYS,
#     #     'mode': 'train',
#     #     'n': 21266432,
#     #     'label': '20m',
#     #     'color': 'darkred',
#     # },
#     '60m': {
#         'path': 'wandb/tiny-olmo-60M-rms-norm-adam-eps-1e-8-lr-6e-4-emb-wd-merged_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 59310080,
#         'label': '60m',
#         'color': 'darkorange',
#     },
#     '150m': {
#         'path': 'wandb/tiny-olmo-150M-rms-norm-adam-eps-1e-8-lr-6e-4-emb-wd-merged_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 151879680,
#         'label': '150m',
#         'color': 'gold',
#     },
#     '300m': {
#         'path': 'wandb/tiny-olmo-300M-rms-norm-adam-eps-1e-8-lr-6e-4-emb-wd-merged_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 319980544,
#         'label': '300m',
#         'color': 'darkgreen',
#     },
#     '700m': {
#         'path': 'wandb/tiny-olmo-700M-rms-norm-adam-eps-1e-8-lr-6e-4-emb-wd-merged_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 681297408,
#         'label': '700m',
#         'color': 'teal',
#     },
#     '1b': {
#         'path': 'wandb/amberish1.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 1176832000,
#         'label': '1b',
#         'color': 'darkblue',
#     },
#     '7b': {
#         'path': 'wandb/amberish7.csv',
#         'keys': VAL_KEYS,
#         'mode': 'eval',
#         'n': 6682316800,
#         'label': '7b',
#         'color': 'darkviolet',
#     },
# }
# CONFIGS = {
#     '150m': {
#         'path': 'wandb/baseline-150M-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 151898880,
#         'label': '150m',
#         'color': 'gold',
#     },
#     '300m': {
#         'path': 'wandb/baseline-300M-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 319980544,
#         'label': '300m',
#         'color': 'darkgreen',
#     },
#     '700m': {
#         'path': 'wandb/baseline-750M-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 681297408,
#         'label': '750m',
#         'color': 'teal',
#     },
#     '1b': {
#         'path': 'wandb/baseline-1B-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'eval',
#         'n': 1176832000,
#         'label': '1b',
#         'color': 'darkblue',
#     },
# }
# CONFIGS = {
#     '150m': {
#         'path': 'wandb/amberish-150M-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 151898880,
#         'label': '150m',
#         'color': 'gold',
#     },
#     '300m': {
#         'path': 'wandb/amberish-300M-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 319980544,
#         'label': '300m',
#         'color': 'darkgreen',
#     },
#     '700m': {
#         'path': 'wandb/amberish-750M-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 681297408,
#         'label': '750m',
#         'color': 'teal',
#     },
#     '1b': {
#         'path': 'wandb/amberish-1B-1xC_val-all.csv',
#         'keys': VAL_KEYS,
#         'mode': 'train',
#         'n': 1176832000,
#         'label': '1b',
#         'color': 'darkblue',
#     },
# }
