run_name: 300m-c4-run-001
seed: 6198
dry_run: false

model:
  d_model: 1024
  n_heads: 16
  n_layers: 24
  mlp_ratio: 4
  alibi: true
  alibi_bias_max: 8.0
  flash_attention: false
  attention_dropout: 0.1
  attention_layer_norm: false
  residual_dropout: 0.1
  embedding_dropout: 0.1
  max_sequence_length: 1024
  include_bias: true
  vocab_size: 50257
  eos_token_id: 50256
  pad_token_id: 50256
  init_device: null
  init_std: 0.02

optimizer:
  learning_rate: 3.0e-4
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08

scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

data:
  paths: ${path.glob:${path.choose:/project/project_462000229/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-train.*.npy}
  pad_direction: right
  num_workers: 2
  drop_last: true
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

tokenizer:
  identifier: gpt2
  truncate_direction: right

save_folder: ${path.choose:/scratch/project_462000229,/results}/${run_name}
save_interval: 1000ba
save_num_checkpoints_to_keep: 2
save_overwrite: true

load_path: null
load_weights_only: false

max_duration: 13400ba # ~ 7B tokens
global_train_batch_size: 512
device_train_batch_size: auto
device_train_microbatch_size: 16  # for 80GB A100 GPU
device_train_grad_accum: auto
device_eval_batch_size: null

n_gpus: null

precision: null

fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: DEFAULT
  activation_checkpointing: false
  activation_cpu_offload: false
  verbose: false

wandb:
  name: ${run_name}

console_log_interval: 10ba
