./scripts/beaker/ladder_peteish-launch.sh 4 --model 190M --data olmoe-mix-0924 --length 1xC --name peteish --save_overwrite --device_batch_size 4 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 370M --data olmoe-mix-0924 --length 1xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 600M --data olmoe-mix-0924 --length 1xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 1xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 1xC --name peteish --save_overwrite --device_batch_size 1 --batch_size_divisor 128

./scripts/beaker/ladder_peteish-launch.sh 4 --model 190M --data olmoe-mix-0924 --length 2xC --name peteish --save_overwrite --device_batch_size 4 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 370M --data olmoe-mix-0924 --length 2xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 600M --data olmoe-mix-0924 --length 2xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 2xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 2xC --name peteish --save_overwrite --device_batch_size 1 --batch_size_divisor 128

./scripts/beaker/ladder_peteish-launch.sh 4 --model 190M --data olmoe-mix-0924 --length 5xC --name peteish --save_overwrite --device_batch_size 4 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 370M --data olmoe-mix-0924 --length 5xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 600M --data olmoe-mix-0924 --length 5xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 5xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 5xC --name peteish --save_overwrite --device_batch_size 1 --batch_size_divisor 128

./scripts/beaker/ladder_peteish-launch.sh 4 --model 190M --data olmoe-mix-0924 --length 10xC --name peteish --save_overwrite --device_batch_size 4 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 370M --data olmoe-mix-0924 --length 10xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 600M --data olmoe-mix-0924 --length 10xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 10xC --name peteish --save_overwrite --device_batch_size 2 --batch_size_divisor 128
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 10xC --name peteish --save_overwrite --device_batch_size 1 --batch_size_divisor 128


./scripts/beaker/ladder_peteish-launch.sh 4 --model 190M --data olmoe-mix-0924 --length 10xC --name peteish-const --save_overwrite --device_batch_size 4 --batch_size_divisor 128 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 8 --model 370M --data olmoe-mix-0924 --length 10xC --name peteish-const --save_overwrite --device_batch_size 2 --batch_size_divisor 128 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 8 --model 600M --data olmoe-mix-0924 --length 10xC --name peteish-const --save_overwrite --device_batch_size 2 --batch_size_divisor 128 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 10xC --name peteish-const --save_overwrite --device_batch_size 2 --batch_size_divisor 128 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 10xC --name peteish-const --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --alpha_f 1.0


./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 50 --eval_interval 50
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 50 --eval_interval 50
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 50 --eval_interval 50
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 50 --eval_interval 50
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 50 --eval_interval 50

./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-rerun --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 100 --eval_interval 100
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-rerun --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 100 --eval_interval 100
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-rerun --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 100 --eval_interval 100
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-rerun --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 100 --eval_interval 100
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-rerun --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 100 --eval_interval 100

./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 2xC --name peteish-moreeval --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 2xC --name peteish-moreeval --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 2xC --name peteish-moreeval --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 2xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 2xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4

./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 5xC --name peteish-moreeval --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 500 --eval_interval 500
./scripts/beaker/ladder_peteish-launch.sh 4 --model 370M --data olmoe-mix-0924 --length 5xC --name peteish-moreeval --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 500 --eval_interval 500
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 5xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 500 --eval_interval 500
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 5xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 500 --eval_interval 500
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 5xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 500 --eval_interval 500

./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 1000 --eval_interval 1000
./scripts/beaker/ladder_peteish-launch.sh 4 --model 370M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 1000 --eval_interval 1000
./scripts/beaker/ladder_peteish-launch.sh 8 --model 760M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 1000 --eval_interval 1000
./scripts/beaker/ladder_peteish-launch.sh 16 --model 1B --data olmoe-mix-0924 --length 10xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 1000 --eval_interval 1000
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 10xC --name peteish-moreeval --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 1000 --eval_interval 1000


./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-const --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 1000 --eval_interval 1000 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-const --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 1000 --eval_interval 1000 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-const --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 1000 --eval_interval 1000 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-const --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 1000 --eval_interval 1000 --alpha_f 1.0
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-const --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 1000 --eval_interval 1000 --alpha_f 1.0


./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 50 --eval_interval 50 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-190M-10xC/step3000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 100 --eval_interval 100 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-190M-10xC/step6000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 2xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 200 --eval_interval 200 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-190M-10xC/step13000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 500 --eval_interval 500 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-190M-10xC/step32000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 190M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 1000 --eval_interval 1000 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-190M-10xC/step65000-unsharded

./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 50 --eval_interval 50 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-370M-10xC/step4000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 100 --eval_interval 100 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-370M-10xC/step8000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 2xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 200 --eval_interval 200 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-370M-10xC/step16000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 500 --eval_interval 500 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-370M-10xC/step42000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 2 --model 370M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 4 --batch_size_divisor 64 --device_eval_batch_size 16 --save_interval 1000 --eval_interval 1000 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-370M-10xC/step84000-unsharded

./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 50 --eval_interval 50 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-760M-10xC/step5000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 100 --eval_interval 100 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-760M-10xC/step10000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 2xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 200 --eval_interval 200 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-760M-10xC/step20000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 500 --eval_interval 500 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-760M-10xC/step52000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 4 --model 760M --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 2 --batch_size_divisor 64 --device_eval_batch_size 8 --save_interval 1000 --eval_interval 1000 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-760M-10xC/step104000-unsharded

./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 50 --eval_interval 50 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-1B-10xC/step7000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 100 --eval_interval 100 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-1B-10xC/step14000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 2xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 200 --eval_interval 200 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-1B-10xC/step29000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 500 --eval_interval 500 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-1B-10xC/step73000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 8 --model 1B --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 64 --device_eval_batch_size 4 --save_interval 1000 --eval_interval 1000 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-1B-10xC/step146000-unsharded

./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 0.5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 50 --eval_interval 50 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-3B-10xC/step9000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 1xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 100 --eval_interval 100 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-3B-10xC/step18000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 2xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 200 --eval_interval 200 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-3B-10xC/step36000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 5xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 500 --eval_interval 500 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-3B-10xC/step90000-unsharded
./scripts/beaker/ladder_peteish-launch.sh 16 --model 3B --data olmoe-mix-0924 --length 10xC --name peteish-moreeval-decay --save_overwrite --device_batch_size 1 --batch_size_divisor 128 --device_eval_batch_size 4 --save_interval 1000 --eval_interval 1000 --alpha_f 0.1 --scheduler_type wsd --load_path /weka/oe-training-default/ai2-llm/checkpoints/OLMo-ladder/peteish-moreeval-const-3B-10xC/step181000-unsharded
