#!/bin/bash

set -x

export MASTER_ADDR=$(hostlist -el1 $SLURM_JOB_NODELIST)
export MASTER_PORT=39591
export WORLD_SIZE=$SLURM_NTASKS
export RANK=$SLURM_PROCID
export LOCAL_WORLD_SIZE=$SLURM_NTASKS_PER_NODE
export LOCAL_RANK=$SLURM_LOCALID
export NODE_RANK=$((($RANK - $LOCAL_RANK) / $LOCAL_WORLD_SIZE))

export ROCR_VISIBLE_DEVICES=$SLURM_LOCALID
exec $*
